lms/accounts/urls.py
from django.contrib import admin
# from lms import settings
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name='home'),
    path('classes/',views.classes,name='classes'),
    path('lessons/<int:id>/',views.lessons,name='lessons'),
    path('profile/',views.update_student,name='student_profile'),
    path('login/',views.login_page,name='login'),
    path('logout/', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('register',views.register_page,name='register'),
]

urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

lms/lms/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls'))
]

lms/accounts/models.py
from django.db import models
from django.contrib.auth.models import User,AbstractUser
from datetime import datetime
import random


def get_path(instance,filename):
    id = instance.student_id
    now = datetime.now()
    time = now.strftime('%d_%H')
    date = now.strftime('%Y_%m')
    end = filename.split('.')[-1]
    return date + '/' + time +'_'+ id + '.' + end


# Create your models here.
# class LMSUser(AbstractUser):
#     is_student = models.BooleanField()
#     is_teacher = models.BooleanField()
#     is_lms_staff = models.BooleanField()
#
#     def __str__(self):
#         return self.username


class Department(models.Model):
    name = models.CharField(max_length=100, null=True, default=' ')

    def __str__(self):
        return self.name


class Major(models.Model):
    name = models.CharField(max_length=100, null=True, default=' ')
    department = models.ForeignKey(Department, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Class(models.Model):
    name = models.CharField(max_length=100, null=True, default=' ')
    major = models.ForeignKey(Major, null=True, on_delete=models.CASCADE)

    def get_lessons(self):
        return self.lesson_set.all()

    def __str__(self):
        return self.name


class Lesson(models.Model):
    name = models.CharField(max_length=100, null=True, default=' ')
    date = models.DateTimeField(null=True)
    relate_class = models.ForeignKey(Class, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Homework(models.Model):
    name = models.CharField(max_length=100, null=True, default=' ')
    start_date = models.DateTimeField(null=True)
    end_date = models.DateTimeField(null=True)
    relate_class = models.ForeignKey(Class, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Exam(models.Model):
    name = models.CharField(max_length=100, null=True, default=' ')
    date = models.DateTimeField(null=True)
    relate_class = models.ForeignKey(Class, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Student(models.Model):
    fname = models.CharField(max_length=100, null=True, default=' ')
    lname = models.CharField(max_length=100, null=True, default=' ')
    user = models.OneToOneField(User,null=True,on_delete=models.CASCADE)
    email = models.EmailField(null=True)
    image = models.ImageField(null=True,upload_to=get_path,default='profile.png')
    student_id = models.CharField(max_length=15, null=True, default=' ')
    department = models.ForeignKey(Department, null=True, on_delete=models.SET_NULL)
    classes = models.ManyToManyField(Class)

    def get_classes(self):
        class_list = self.classes.all()
        return class_list

    def get_lessons(self):
        class_list = self.get_classes()
        lessons = class_list.none()
        for cls in class_list:
            lessons = lessons | cls.get_lessons()
        return lessons

    def __str__(self):
        return str(self.fname) + ' ' + str(self.lname)


class Teacher(models.Model):
    fname = models.CharField(max_length=100, null=True, default=' ')
    lname = models.CharField(max_length=100, null=True, default=' ')
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    teacher_id = models.CharField(max_length=15, null=True, default=' ')
    department = models.ForeignKey(Department, null=True, on_delete=models.SET_NULL)
    classes = models.ManyToManyField(Class)

    def __str__(self):
        return str(self.fname) + ' ' + str(self.lname)


class Staff(models.Model):
    fname = models.CharField(max_length=100, null=True, default=' ')
    lname = models.CharField(max_length=100, null=True, default=' ')
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    teacher_id = models.CharField(max_length=15, null=True, default=' ')
    department = models.ForeignKey(Department, null=True, on_delete=models.SET_NULL)
    classes = models.ManyToManyField(Class)

    def get_classes(self):
        class_list = self.classes.all()
        return class_list

    # def get_lessons(self):
    #     lessons = None
        # class_list = self.get_

    def __str__(self):
        return str(self.fname) + ' ' + str(self.lname)


class HomeworkAnswer(models.Model):
    description = models.CharField(max_length=1000, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    file = models.FileField()
    student = models.ForeignKey(Student, null=True, on_delete=models.CASCADE)

lms/accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django import forms
from django.contrib.auth.models import User
from .models import *


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ['fname', 'lname', 'email','image']
        widgets = {
            'image' : forms.FileInput(attrs={'class':'form-control-file'})
        }


class TeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = '__all__'
        widgets = {
            'fname': forms.TextInput(attrs={'type': 'text'}),
        }


# class UserForm()


class CreateUser(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username' : forms.TextInput(attrs={'type':'text','placeholder':'e.g : Jack123'}),
            'email': forms.TextInput(attrs={'type': 'text', 'placeholder': 'e.g : example@fakemail.com'}),
            'password1' : forms.TextInput(attrs={'type':'password'}),
            'password2': forms.TextInput(attrs={'type': 'password'})
        }

lms/accounts/views.py
from django.shortcuts import render,redirect
from .models import *
from .forms import *
from django.contrib.auth.models import Group
from django.contrib.auth import authenticate,login
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def home(request):
    student = request.user.student
    classes = student.get_classes()
    # lessons = classes.lesson_set.all()

    # context = {'students':student,'classes':classes,'lessons':lessons}
    context = {'student': student, 'classes': classes}
    return render(request,'accounts/student.html',context)


@login_required
def classes(request):
    student = request.user.student
    classes = student.get_classes()
    context = {'students': student, 'classes': classes,}
    return render(request, 'accounts/classes.html', context)


@login_required
def lessons(request,id):
    # lessons = request.user.student.get_lessons()     # this will be used in Home page
    lessons = Class.objects.get(id=id).get_lessons()

    context = {'lessons':lessons}
    return render(request,'accounts/lessons.html',context)


@login_required
def update_student(request):
    student = request.user.student
    form = StudentForm(instance=student)
    if request.method == 'POST' :
        form = StudentForm(request.POST, request.FILES, instance=student)
        if form.is_valid():
            form.save()
            return redirect('home')
    context = {'form': form}
    return render(request,'accounts/profile.html',context)


def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request,username=username,password=password)
        if user is not None :
            # print('***   ',user.id)
            login(request,user)
            # print('user : ',user)
            return redirect('home')
    return render(request, 'accounts/login.html')


def register_page(request):
    form = CreateUser()

    if request.method == 'POST':
        form = CreateUser(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')

    context = {'form' : form}
    return render(request,'accounts/register.html',context)

lms/accounts/templates/accounts/classes.html
{% extends 'accounts/template.html' %}

{% block title %}
Classes
{% endblock %}

{% block content %}
<div class="col">
		<h5>Classes of {{ request.user.student }}:</h5>
		<hr>
		<div class="card card-body">
{#			<a class="btn btn-primary  btn-sm btn-block" href="">Create Customer</a>#}
			<table class="table table-sm">
				<tr>
					<th></th>
					<th>Class</th>
					<th>Teacher</th>
                    <th>View</th>
				</tr>

                {% for classname in classes %}
                <tr>
					<td></td>
					<td>{{ classname }}</td>
					<td>{{ classname.teacher_set.first }}</td>
                    <td><a class="btn btn-primary  btn-sm" href="{% url 'lessons' classname.id %}">View</a></td>
				</tr>

                {% endfor %}
            </table>
        </div>
</div>
{% endblock %}

lms/accounts/templates/accounts/lessons.html
{% extends 'accounts/template.html' %}

{% block title %}
Lessons
{% endblock %}

{% block content %}
<br>
<div class="col">
		<h5>Classes of {{ request.user.student }}</h5>
		<hr>
		<div class="card card-body">
{#			<a class="btn btn-primary  btn-sm btn-block" href="">Create Customer</a>#}
			<table class="table table-sm">
				<tr>
					<th></th>
					<th>Lesson</th>
					<th>Class</th>
                    <th>link</th>
				</tr>

                {% for lesson in lessons %}
                <tr>
					<td></td>
					<td>{{ lesson }}</td>
					<td>{{ lesson.relate_class }}</td>
                    <td>---</td>
				</tr>

                {% endfor %}
            </table>
        </div>
</div>
{% endblock %}

lms/accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static '/css/logstyle.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

<div class="jumbotron jumbotron-fluid p-3">
    <h1 align="center">Login page</h1>
    <p class="text-black-50" align="center">let's log in</p>
</div>

<fieldset style="margin: auto;">
    <div class="wrapper bg-white">
        <div class="h4 text-muted text-center pt-2">Enter your login details</div>
        <form class="pt-3" method="post" action="">
            {% csrf_token %}
            <div class="form-group py-2">
                <div class="input-field"> <span class="far fa-user p-2"></span>
                    <input type="text" placeholder="Username" required name="username"> </div>
            </div>
            <div class="form-group py-1 pb-2">
                <div class="input-field"> <span class="fas fa-lock p-2"></span>
                    <input type="password" placeholder="Enter your Password" required class="" name="password">
                </div>
            </div>
            <div class="d-flex align-items-start">
                <div class="custom-control custom-checkbox mb-3">
                    <input type="checkbox" class="custom-control-input" id="customCheck" name="example1">
                    <label class="custom-control-label" for="customCheck">Remember me</label>
                </div>
                <div class="ml-auto"> <a href="" onclick="window.alert('This is none of my business! You should have remembered it!')"
                                         id="forgot">Forgot Password?</a>
                </div>

            </div>

            {% for message in messages %}
                <p class="text-danger">{{ message }}</p>
            {% endfor %}

            <button class="btn btn-block text-center my-3">Log in</button>
            <div class="text-center pt-3 text-muted">Not a member? <a href="{% url 'register' %}" target="_blank">Sign up</a></div>
        </form>

    </div>
</fieldset>

</body>
</html>

lms/accounts/templates/accounts/navbar.html
<nav class="navbar smart-scroll navbar-expand-sm navbar-dark bg-dark">
        <div class="collapse navbar-collapse" id="main_nav">
            <ul class="navbar-nav">

                <li class="nav-item"> <a class="nav-link" href="{% url 'home' %}"> Home </a> </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'student_profile' %}"> Profile </a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'classes' %}"> Classes </a></li>
                <li class="nav-item"><a class="nav-link" href="#"> Homework </a></li>                         <!-- link to scroll     -->



            </ul>
        </div>

        <div class="text-white" style="margin-right: 38%; font-size: 20px;">LMS</div>

         {% if request.user.is_authenticated %}
            <span style="color: white; margin-right: 20px">Hello {{ request.user }}</span>
            <span ><a href="{% url 'logout' %}" class="text-light nav-link" style="margin-right: 20px">Log out</a> </span>
        {% endif %}

</nav>

lms/accounts/templates/accounts/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static '/css/signupstyle.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <meta charset="UTF-8">
    <title>Update profile</title>
</head>
<body>

<div class="jumbotron jumbotron-fluid p-3">
    <h1 align="center">Update your profile</h1>
{#    <p class="text-black-50" align="center">Register for no reason...</p>#}
</div>
        <fieldset style="margin: auto;">
    <div class="wrapper bg-white">
        <div class="h4 text-muted text-center pt-2">Fill the form</div>
        <form class="pt-3" method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group py-2">
                <label class="text-secondary">First name:</label>
                <div class="input-field">
{#                    <input type="text" placeholder="e.g:Jack123" required>#}
                    {{ form.fname }}
                </div>
            </div>

            <div class="form-group py-2">
                <label class="text-secondary">Last name:</label>
                <div class="input-field">
{#                    <input type="text" placeholder="e.g:Jack123" required>#}
                    {{ form.lname }}
                </div>
            </div>


             <div class="form-group py-2">
                <label class="text-secondary">Email:</label>
                <div class="input-field">
{#                    <input type="text" placeholder="e.g:Jack123" required>#}
                    {{ form.email }}
                </div>
            </div>

            <div class="form-group py-2">
                <label class="text-secondary">pic:</label>
                <div class="form-control-file">
{#                    <input type="file" class="form-control-file" required>#}
                    {{ form.image }}
                </div>
            </div>


            <button class="btn btn-block text-center my-3" type="submit">Submit</button>
        </form>

    </div>
</fieldset>

</body>
</html>

lms/accounts/templates/accounts/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static '/css/signupstyle.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <meta charset="UTF-8">
    <title>Sign Up</title>
</head>
<body>

<div class="jumbotron jumbotron-fluid p-3">
    <h1 align="center">signup page</h1>
    <p class="text-black-50" align="center">Register for no reason...</p>
</div>

<fieldset style="margin: auto;">
    <div class="wrapper bg-white">
        <div class="h4 text-muted text-center pt-2">Fill the form</div>
        <form class="pt-3" method="POST" action="">
            {% csrf_token %}
            <div class="form-group py-2">
                <label class="text-secondary">Username:</label>
                <div class="input-field">
{#                    <input type="text" placeholder="e.g:Jack123" required>#}
                    {{ form.username }}
                </div>
            </div>

            <div class="form-group py-2">
                <label class="text-secondary">Email:</label>
                <div class="input-field">
{#                    <input type="text" placeholder="e.g:Jack123" required>#}
                    {{ form.email }}
                </div>
            </div>

            <div class="form-group py-1 pb-2">
                <label class="text-secondary">Password:</label>
                <div class="input-field">
{#                    <input type="password" placeholder="****" required class="">#}
                    {{ form.password1 }}
                </div>
            </div>
            <div class="form-group py-1 pb-2">
                <label class="text-secondary">Password verify:</label>
                <div class="input-field">
{#                    <input type="password" placeholder="****" required class="">#}
                    {{ form.password2 }}
                </div>
            </div>

{#            <div class="alert alert-danger">#}
{#                <strong>{{ form.errors }}</strong>#}
{#            </div>#}

            <button class="btn btn-block text-center my-3" type="submit">SIGN UP</button>
            <div class="text-center pt-3 text-muted">Already have an account? <a href="{% url 'login' %}" target="_blank">Log in</a></div>
            <div class="text-center pt-3">
                <label class="text-muted ">want to reset?  <button class="btn btn-light" type="reset">Reset</button></label>
            </div>
        </form>

    </div>
</fieldset>

</body>
</html>

lms/accounts/templates/accounts/student.html
{% extends 'accounts/template.html' %}
{% load static %}

{% block title %}
Home
{% endblock %}

{% block content %}

<div class="jumbotron jumbotron-fluid p-3">
    <h1 align="center">{{ request.user }}'s page</h1>
{#    <p class="text-black-50" align="center"> Blah Blah Blah...</p>#}
</div>


{#    <div class="container">#}

    <div class="row" style="width: 100%;">
        <div class="col-md-3">
            <img src="{{ student.image.url }}" class="rounded-circle" style="width: 250px;height: 250px; margin-left: 10%;">
            <br>
            <br>
            <a class="btn btn-success" href="{% url 'student_profile' %}" style="margin-left: 23%;">Change profile</a>
        </div>
        <div class="col-md-9">

            <div class="row">
                <div class="col-md-3" style=" border-radius: 13px;background: #30dfff;">
                    <h6 style="text-align: center; margin-top: 5px;" class="text-secondary">First name</h6>
                    <hr>
                    <p style="text-align: center" class="text-dark">{{ student.fname }}</p>
                </div>

                <div class="col-md-1"></div>

                <div class="col-md-3" style=" border-radius: 13px;background: #30dfff;">
                    <h6 style="text-align: center; margin-top: 5px;" class="text-secondary">Last name</h6>
                    <hr>
                    <p style="text-align: center" class="text-dark">{{ student.lname }}</p>
                </div>

                <div class="col-md-1"></div>

                <div class="col-md-3" style=" border-radius: 13px;background: #30dfff;">
                    <h6 style="text-align: center; margin-top: 5px;" class="text-secondary">Student ID</h6>
                    <hr>
                    <p style="text-align: center" class="text-dark">{{ student.student_id }}</p>
                </div>
            </div>
            <div style="height: 20px;"></div>
                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md-3" style=" border-radius: 13px;background: #30dfff;">
                    <h6 style="text-align: center; margin-top: 5px;" class="text-secondary">Email</h6>
                    <hr>
                    <p style="text-align: center" class="text-dark">{{ student.email }}</p>
                </div>

                    <div class="col-md-2"></div>

                    <div class="col-md-3" style=" border-radius: 13px;background: #30dfff;">
                    <h6 style="text-align: center; margin-top: 5px;" class="text-secondary">Department</h6>
                    <hr>
                    <p style="text-align: center" class="text-dark">{{ student.department }}</p>
                </div>

                </div>

            </div>

        </div>
    </div>

{#    </div>#}





<div class="col">
<br>
		<h5>Classes of {{ request.user }}</h5>
		<hr>
		<div class="card card-body">
			<table class="table table-sm">
            <thead class="thead-dark">
				<tr>
					<th></th>
					<th>Class</th>
					<th>page</th>
{#                    <th>date</th>#}
				</tr>
                </thead>

                {% for cls in classes %}
                <tr>
					<td></td>
					<td>{{ cls }}</td>
                    <td><a class="btn btn-primary  btn-sm" href="{% url 'lessons' cls.id %}">View</a></td>
				</tr>

                {% endfor %}
            </table>
        </div>
</div>
{% endblock %}

lms/accounts/templates/accounts/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>
<body>
{% include 'accounts/navbar.html' %}
{% block content %}

{% endblock content %}

</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>